version: "3"
services:
   mongodb:
      image: mongo
      ports:
         - 270170:270170
      environment:
         - MONGO_INITDB_ROOT_USERNAME="admin"
         - MONGO_INITDB_ROOT_PASSWORD="12345"

   mongo-express:
      image: mongo-express
      ports: 
         - 8081:8081
      environment:
         - ME_CONFIG_MONGODB_SERVER="mongodb"
         - ME_CONFIG_BASICAUTH_USERNAME="admin"
         - ME_CONFIG_BASICAUTH_PASSWORD="12345"